# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: postgres_db
    image: 'postgres:15.3-alpine3.18'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dating_apps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    container_name: redis_cache
    image: 'redis:7.0.11-alpine3.18'
    volumes:
      - 'redis-data:/data'
    ports:
      - '6379:6379'
volumes:
  postgres-data: null
  redis-data: null