name: Linter Runner

on:
  push:
    branches:
      - main
      - master
      - development
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: copy .env.example to .env
        run: cp .env.example .env

      - name: install swagger
        run: go get -u github.com/swaggo/swag/cmd/swag

      - name: generate swagger documentation
        run: swag init

      - name: install wire
        run: go get -u github.com/google/wire/cmd/wire

      - name: generate wire
        run: wire

      - name: Lint Prepare
        run: make lint-prepare

      - name: Run Linter
        run: make lint

